### ISSUE TITLE
having a problem with PAL version RNG

### ISSUE THREAD

**Issue by q8yshadow** [aldelaro5/GC-pokemon-RNG-manipulation-assistant#12]
i've been trying to figure out how to RNG eevee on PAL version of pokemon XD but it always show one frame and it's not the right result either so....i tried searching online for guides or anything but there's nothing on how to do it :( i did do the US version and got it correctly but couldn't figure out on doing it for PAL version.

not sure where else to contact you so i figured to post it here if you have any idea on giving me steps? also if i were to try doing it on JPN version of XD which one do i use on the RNG? US or PAL version?

**Comment by aldelaro5** [comment]
I will close this because this isn't an issue, it's how the game works.

SPECIFICALLY on XD PAL (so colo or xd ntsc-u and xd ntsc-j don't apply here), the game doesn't roll the rng during the naming screen. This does one very good thing and one very bad thing: it means you will get a hassle free manip because you won't need to hit a specific frame, but it also means that you only get ONE variant per reroll. In practice, it means if you are picky with your criterias (which is common in speedrunning), you will likely need to do hundreds or thousands of rerolls.

This is btw clearly explained in the instructions and it is why there is a setting specifically for pal version on xd (because it's to not show wrong informations).

There is however a way you could reduce the amount of rerolls and it has to do with watching a moltres, the burning wings causes rng to roll in such a way that you can get CLOSER to your desired result, but unfortunately, I don't have all the details and it's not currently documented in the program. Still, it doesn't really change what the program is doing.
